# Generated by Django 6.0.4 on 2026-05-11 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_sitevisit_estimate'),
        ('project_app', '0002_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_app.estimate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
    ]
