# Generated by Django 6.0.4 on 2026-05-10 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0002_remove_invoice_issued_date_remove_invoice_paid_and_more'),
        ('project_app', '0002_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='project_app.project'),
            preserve_default=False,
        ),
    ]
